### ISSUE TITLE
Zustand 설치 및 폴더 구조 정리

### ISSUE THREAD

**Issue by bbearcookie** [dnd-side-project/dnd-10th-4-frontend#15]
# 📦️ Chore

## 어떤 작업을 할 예정인가요?
- Recoil 삭제
- Zustand 설치
- 폴더 구조 정리

**Comment by easyhyun00** [comment]
@bbearcookie 

### Zustand 를 어디에서 사용하면 좋을까요? 

일단 제가 생각한 곳은

1. 사용자 정보 상태 관리 - 온보딩, 마이페이지 등(닉네임, 생년월일, 고민종류, 성별 등) 
2. 편지 작성 내용 상태 관리 - 보내는 이(연령, 성별, 고민종류 등), 편지 내용
3. 글로벌 상태 관리 - 배경음악(Zustand, 로컬스토리지 결합하여 사용)

**Comment by bbearcookie** [comment]
오.. 저도 이와 관련한 고민이 있었는데 먼저 코멘트 남겨주셔서 감사해요!! 😁

1.  사실 **서버로부터 가져오는 데이터**를 상태로 관리하는 데 있어서 **TanStack Query**를 사용하고,
2.  **폼 데이터**를 관리하는 데 있어서 **React Hook Form**을 사용한다면.. 

위 두 라이브러리가 사실 용도에 맞도록 상태를 알아서 관리해주는 역할도 겸할 수 있다보니..
클라이언트 단에서 전역으로 빼야 할 상태가 무엇인가.. 에 대해서 늘 고민이 되었어요.

먼저, 지현님이 생각해 주셨던 부분에 대해서 저도 함께 고민해보자면

## 1. 사용자 정보 상태 관리(닉네임, 생년월일, 고민종류, 성별 등)
- 이 부분은 백엔드 서버에 존재하는 데이터이기에, `TanStack Query` 를 사용해서 관리한다면 추가적인 전역 스토어는 없어도 충분할 것 같아요. (특정 쿼리 키에 캐싱된 데이터를 가져온다거나..)
- TanStack Query V5에서 `useQuery()` 함수의 onSuccess 콜백이 사라진 이유도 **서버 상태를 임의의 클라이언트 사이드 상태 관리 도구에 넣어서 사용하려는 패턴**때문으로 알고 있어요! [(참고자료)](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose#state-syncing)
- 따라서.. TanStack Query의 스토어와, Zustand의 스토어의 동기화가 깨지는 상황을 방지하기 위해 서버로부터 가져오는 데이터는 그냥 `TanStack Query` 만 사용해도 충분할 것 같아요.

### 그런데 온보딩 페이지에서는

![image](https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/50488780/7001b5f5-da55-405c-8ed1-1ff513e4dbde)

온보딩 페이지에서는 퍼널 이동시 새로운 스텝 컴포넌트를 렌더링 해야 할텐데, 이 경우에는 **각 스텝 간 상태를 공유**해야 할 필요가 있어 보여요.
그런데 사실 이 부분도 React Hook Form을 사용한다면 [FormProvider](https://react-hook-form.com/docs/formprovider)를 이용해서 상태를 공유하면 되어서.. Zustand 까지는 필요 없을 것 같긴 하네요..

## 2. 편지 작성 내용 상태 관리 - 보내는 이(연령, 성별, 고민종류 등), 편지 내용
요 부분도 마찬가지로 폼 데이터와 관련한 내용이어서 `React Hook Form` 으로 충분할 것 같아요!

(특히, React Hook Form은 기본적으로 폼 내용이 바뀌어도 리렌더링하지 않는 비제어 컴포넌트 방식으로 작동하기에, 최적화에도 좋을 것 같네요!)

## 3. 글로벌 상태 관리 - 배경음악(Zustand, 로컬스토리지 결합하여 사용)

저도 이 부분에 Zustand를 활용하면 좋겠다는 생각이 들었어요!

그 이유 두 가지는 아래와 같아요:
1. 배경 음악의 On/Off에 대한 정보는 클라이언트만 갖고 있고, 서버는 몰라도 되는 데이터이기 때문.
2. 배경 음악의 On/Off에 대한 정보를 스토리지에 기록하고 있으면 좋을 듯 하니.. Zustand의 [Persist Middleware](https://github.com/pmndrs/zustand?tab=readme-ov-file#persist-middleware) 를 이용하면 좋을 것 같기 때문.

## 마무리

사실.. 어떤 데이터를 전역 스토어에서 관리해야 할 지 명확하게 감이 오지는 않긴 해요 😂
저는 그래서 이전 프로젝트에서도 특별한 전역 상태 관리 라이브러리는 사용하지 않고 Context API만 사용해 왔었거든요..

다만, 최근에 느꼈던 것은 Context API를 사용하는 데 있어서 몇 가지 불편한 점이 있었다는 부분이에요.

> 1. Context를 생성하고 Provider를 만들어서 주입하기까지 필요한 보일러 플레이트가 번거로움.
> 2. Provider가 많아진다면 그 만큼 JSX 트리가 깊어지는 것이 번거로움.
> 3. Provider의 value 가 바뀌면 하위 트리는 모두 리렌더링되기에, 렌더링 효율성을 위해서 Provider를 국소적으로 잘 나눠야하는 게 번거로움.

그래서.. Zustand로 클라이언트 사이드의 전역 상태를 관리하는 데 있어서는 컴포넌트의 Depth가 깊어져서 **Props Drilling 현상이 일어나는 걸 방지하면서도, 컴포넌트의 리렌더링을 최소화**하는 데 초점을 맞추면 어떨까? 싶어요.

**Comment by bbearcookie** [comment]
아래는 2023 우아콘에서 발표된 TanStack Query랑 Zustand를 함께 활용한 사례인데요!
https://youtu.be/nkXIpGjVxWU?si=uEpDpvIW4sbqS8QE&t=1051

사실 비즈니스 로직이 엄청 복잡한 건 아니다보니.. 영상을 봐도 어떻게 적용해야 할지 감이 안오는 부분은 있지만 그래도 공유드려요!!

**Comment by bbearcookie** [comment]
컴포넌트의 확장성을 고려하기 위해 [Compound 패턴](https://patterns-dev-kr.github.io/design-patterns/compound-pattern/) 을 이용할 때에도 Zustand를 이용할 수 있지 않을까 싶어서 [공식 가이드 문서](https://docs.pmnd.rs/zustand/guides/initialize-state-with-props) 를 찾아봤는데.. 요런 방법으로 활용할 수도 있겠네요!

하단에 Playground용 코드를 작성해보았는데.. `DiForm` 에서 Zustand 스토어를 생성한 뒤, 자식 컴포넌트에게 의존성을 주입해주면 자식 컴포넌트에서는 불필요한 리렌더링 없이 필요한 상태만 뽑아 쓸 수 있는 기능으로 활용할 수 있네요!

## 예시 코드

### 사용하는 쪽
```tsx
<DiForm username="하이" password="1234">
  <h3>반가워요</h3>
  <div style={{ background: 'gainsboro', padding: '1rem' }}>
    <DiForm.Username />
    <DiForm.Password />
  </div>
  <DiForm.SubmitButton />
</DiForm>

<DiForm username="의존성 주입" password="ㅋㅋㅋ">
  <h3>두 번째 폼이에요 (합성 패턴)</h3>
  <div style={{ background: 'greenyellow', padding: '1rem' }}>
    <DiForm.Username />
    <DiForm.Password />
  </div>
  <DiForm.SubmitButton />
```

### DiForm 컴포넌트
```tsx
import { useRef } from 'react';
import createFormStore, { FormContext, type FormProps } from './formStore';
import DiUsername from './DiUsername';
import DiPassword from './DiPassword';
import DiSubmitButton from './DiSubmitButton';

interface DiFormProps extends FormProps {
  children?: React.ReactNode;
}

const DiForm = ({ children, ...props }: DiFormProps) => {
  const store = useRef(createFormStore(props)).current;

  return <FormContext.Provider value={store}>{children}</FormContext.Provider>;
};

export default DiForm;

DiForm.Username = DiUsername;
DiForm.Password = DiPassword;
DiForm.SubmitButton = DiSubmitButton;
```

### DiUsername 컴포넌트
```tsx
import { useContext } from 'react';
import { useStore } from 'zustand';
import { FormContext } from './formStore';

const DiUsername = () => {
  const store = useContext(FormContext);
  if (!store) throw new Error('Missing FormContext.Provider in the tree');

  const username = useStore(store, (s) => s.username);
  const setUsername = useStore(store, (s) => s.setUsername);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setUsername(e.target.value);
  };

  return (
    <input
      value={username}
      onChange={handleChange}
      placeholder="아이디 입력하세요"
      style={{ border: 'none', height: '50px' }}
    />
  );
};

export default DiUsername;
```

## 실행 결과
![리렌더링](https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/50488780/7ffcc7b6-f63d-471b-9532-0e27a5a5bad7)

**Comment by easyhyun00** [comment]
@bbearcookie 

# 1. 사용자 정보 상태 관리(닉네임, 생년월일, 고민종류, 성별 등)
> 이 부분은 백엔드 서버에 존재하는 데이터이기에, TanStack Query 를 사용해서 관리한다면 추가적인 전역 스토어는 없어도 충분할 것 같아요. (특정 쿼리 키에 캐싱된 데이터를 가져온다거나..)

메인 페이지 같은 곳에 혹시라도 _${useNickname}님 안녕하세요!_ 이런 것이 있다면 상태관리 라이브러리를 이용해 쉽게 사용할 수 있는데,  `TanStack Query` 에서 캐싱된 데이터를 가져올 수 있으니 굳이 `Zustand` 를 사용할 이유가 없는 것 같네요!

> 온보딩 페이지에서는 퍼널 이동시 새로운 스텝 컴포넌트를 렌더링 해야 할텐데, 이 경우에는 각 스텝 간 인풋의 상태를 공유해야 할 필요가 있어 보여요

아! 저는 **온보딩 페이지**를 **싱글 페이지**에서 모두 렌더링하는 것이 아니라 **멀티 페이지**로 각 스텝을 페이지별로 구현하는 걸로 생각하고 있었어요! 입력 받은 내용을 `Zustand` 를 사용하면 페이지 간 상태를 공유하는 게 쉽기 때문이에요.

그래서 **싱글 페이지 vs 멀티 페이지** 이 두가지를 고려해봐야 될 것 같네요! (싱글 페이지는 `React Hook Form의 FormProvider`, 멀티 페이지는 `Zustand` 사용하는 게 맞겠네요)

## 싱글 페이지 vs 멀티 페이지
1. **사용자 경험** - 페이지 전환이 없으니 싱글 페이지가 더 좋아요. 그런데 멀티 페이지도 사용자 경험이 나쁘진 않을거예요. (크게 복잡한 내용이 없어서)
2. **프로세스의 복잡도** - 복잡할 수록 멀티페이지에서 관리하는 게 편한데 저희 온보딩 페이지는 복잡하진 않네요.
3. **리렌더링** - `FormProvider` 를 사용할 경우 리렌더딩이 발생한다고 하는데 이게 큰 form 에서는 성능 저하를 일으키겠지만 저희는 크게 상관 없을 것 같지만 이러한 것을 고려한다면 `Zustand` 사용하는 게 좋을 것 같네요
4. **초기 로딩 시간** - 싱글 페이지가 더 긴데 사실 그렇게 복잡한 내용을 담고 있진 않아서 큰 차이를 느낄 정도는 아니긴 하네요
5. **개발과 유지 보수** - 음 뭐가 좋은지 모르겠네요...

등등。。。

# 2. 편지 작성 내용 상태 관리 - 보내는 이(연령, 성별, 고민종류 등), 편지 내용
 
 이거는 `React Hook Form` 으로 관리하면 되겠네요!
 
 # 3. 글로벌 상태 관리 - 배경음악(Zustand, 로컬스토리지 결합하여 사용)
 
 `Zustand의 Persist Middleware` 이 기능 모르고 있었는데 간편하게 로컬 스토리지에 저장할 수 있겠네요! 
 
 # Props Drilling & TanStack Query랑 Zustand
> 컴포넌트의 Depth가 깊어져서 Props Drilling 으로 인한 불편함을 방지하면서도, 컴포넌트의 리렌더링을 최소화하는 데 초점을 맞추면 어떨까? 싶어요.

>TanStack Query랑 Zustand를 함께 활용한 사례

이 두가지 경우를 고려했을 때 이런식으로 사용하면 될까요? 간단하게 구현해봤어요

```
// 편지보관페이지
const { data } = useQuery(옵션들어감)
const setLetters = useStore(state => state.setLetters)

if (data) {
  setLetters(data)
}

<div>
  <상단탭 컴포넌트 />
  <ContentComponent />
</div>
```

```
// ContentComponent
<div>
  <이런저런 내용 />
  <LetterList />
</div>
```

```
// LetterList
const letters = useStore(state => state.letters)

<div>
  {letters.map((letter, index) => (
    <LetterItem key={index} letter={letter} />
   ))}
</div>
```

```
// LetterItem
<div>
  <이런저런 내용 컴포넌트 />
</div>

```

# Compound 패턴

오 이렇게 할 수도 있군요 👍

**Comment by bbearcookie** [comment]
@easyhyun00 

> 싱글 페이지 vs 멀티 페이지
> (싱글 페이지는 React Hook Form의 FormProvider, 멀티 페이지는 Zustand 사용하는 게 맞겠네요)

아하~ 온보딩 페이지를 라우팅 경로에 따라서 다른 페이지 컴포넌트를 보여주도록 관리할 수도 있겠군요! 👍
그렇다면 여러 페이지끼리 데이터 공유를 위해서 Zustand가 필요한 부분이 될 수 있겠네요 👍👍

> Props Drilling & TanStack Query랑 Zustand

저도 구현해 주신 방향처럼 **상위 컴포넌트가 주입한 데이터를 하위 컴포넌트에서 사용할 수 있는 느낌**으로 활용하면 좋다고 생각해요!! 😁

그런데.. 예시에서는 TanStack Query가 캐싱하고 있는 **서버 데이터를 클라이언트 상태 관리 도구에 추가 보관하는 느낌**이어서.. 
[TanStack Query 메인테이너](https://tkdodo.eu/blog/breaking-react-querys-api-on-purpose#state-syncing)가 권장하지 않는 방법이라고 생각돼요!!

![image](https://github.com/dnd-side-project/dnd-10th-4-frontend/assets/50488780/be3085a7-8998-4e04-b939-f8ae12d4bb2a)

이 경우에는 편지 목록이라는 **서버 데이터가 필요한 컴포넌트에서 직접 `useQuery`를 호출** 해도 괜찮을 것 같아요! (필요에 따라서 적절한 staleTime 값 부여..)

```tsx
// LetterList
const { data: letters } = useQuery(옵션들어감)

<div>
  {letters.map((letter, index) => (
    <LetterItem key={index} letter={letter} />
   ))}
</div>
```

**Comment by easyhyun00** [comment]
> 예시에서는 TanStack Query가 캐싱하고 있는 서버 데이터를 클라이언트 상태 관리 도구에 추가 보관하는 느낌이어서..
TanStack Query 메인테이너가 권장하지 않는 방법이라고 생각돼요!!

아 v4까지 있던 onSuccess, onError, onSettled Callback 가 없어졌고, 추가적인 상태 업데이트(setLetters)로 불필요한 리렌더링을 발생시킬 수 있겠네요 그리고 공식문서에서도 권장하지 않군요..

>이 경우에는 편지 목록이라는 서버 데이터가 필요한 컴포넌트에서 직접 useQuery를 호출 해도 괜찮을 것 같아요! (필요에 따라서 적절한 staleTime 값 부여..)

네 필요한 컴포넌트에서 호출하면 **Zustand** 를 사용할 필요도 없겠군요! 그리고 편지가 실시간으로 꼭 볼 수 있어야 되는 기능까진 아니면 `staleTime` 값을 적당히 길게 설정하면 좋을 거 같네요

**Comment by bbearcookie** [comment]
하하.. 사실 전역으로 빼야 할 상태가 아직 배경 음악이나 테마같은 부분밖에 생각이 안나긴 하는데..
개발 단계에서 들어가면서 컴포넌트의 Props Drilling이 심하다거나, 전역으로 빼면 좋겠는 상태가 생기면 그 때 Zustand를 활용해보면 어떨까요??

**Comment by easyhyun00** [comment]
@bbearcookie 

음 그러게요.. 전역으로 관리해야 될 게 일단 `배경 음악`이고 `Props Drilling` 이 심한 경우인데 저희 컴포넌트가 그렇게 복잡한 편은 아닐 것 같아서 애매하긴 하네요 일단 배경음악은 `Zustand` 사용하고 추후에 도입할 곳에 필요하다면 그 때 사용하면 좋겠네요
